### ISSUE TITLE
No media icon on webpage

### ISSUE THREAD

**Issue by Rafalkufel** [CodeForPoznan/codeforpoznan.pl_v2#26]
![zrzut ekranu z 2017-12-06 21-11-41](https://user-images.githubusercontent.com/30240475/33683123-1ee10d28-daca-11e7-9c11-9b361d40c21e.png)

Media icon are lacking in the media containter.

**Comment by magul** [comment]
It requires node, npm and gulp

after installing it and building through gulp all icons looks fine.
