### ISSUE TITLE
Rename gitter room

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/codeforpoznan.pl_v2#35]
see: https://gitter.im/gitterHQ/topics/topic/580ef9ea472236f05c9e4788/what-happens-if-i-rename-something-on-github-org-repo

**Comment by w1stler** [comment]
Done as in FAQ

**Comment by w1stler** [comment]
`Eric Eastwood (Gitter)

Jan 9, 06:09 WET

Hey Wojciech,

https://gitter.im/CodeForPoznan/codeforpoznan.pl_v2 is setup and ready to go tada

Warm Regards,
- Eric`
