### ISSUE TITLE
Social media icons are not aligned

### ISSUE THREAD

**Issue by StaszkoSamoZuo** [CodeForPoznan/codeforpoznan.pl_v2#62]
or the gitter icon is constantly selected

<img width="449" alt="Screen Shot 2019-08-02 at 10 40 54" src="https://user-images.githubusercontent.com/42676801/62356732-089c2380-b512-11e9-9a74-8683d05d51c1.png">

**Comment by magul** [comment]
That exists on our live site, but the development environment doesn't contain such an issue. The way how we sync assets to live site should be checked.

**Comment by arturtamborski** [comment]
Fixed in https://github.com/CodeForPoznan/codeforpoznan.pl_v2/pull/69.
