### ISSUE TITLE
Gitter icon redirects to the not existing page 

### ISSUE THREAD

**Issue by StaszkoSamoZuo** [CodeForPoznan/codeforpoznan.pl_v2#63]
<img width="1251" alt="Screen Shot 2019-08-02 at 10 45 19" src="https://user-images.githubusercontent.com/42676801/62357096-ab54a200-b512-11e9-8037-8c373c758110.png">

**Comment by magul** [comment]
That's a well-known problem for Gitter, that if you don't have access to a resource, it goes to an infinite redirect loop. Don't really know if we're going to approach it, as we abandon Gitter in favor of Slack.
